language: go

notifications:
  email:
    - alkemic7+travis-ci-notifications@gmail.com

go:
  - "1.3"
  - "1.4"
  - "1.5"
  - "1.6"

before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - if ! go get github.com/golang/tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi

install:
  - go get github.com/stretchr/testify/assert

script:
  - "$HOME/gopath/bin/goveralls -service=travis-ci"
  - go test -coverprofile=coverage.out
  - /opt/sonar-scanner/bin/sonar-scanner -Dsonar.projectKey=go-forms -Dsonar.projectName="GoLang forms" -Dsonar.organization=alkemic-github -Dsonar.sources=. -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN -Dsonar.test.exclusions=**_test.go,coverage.out -Dsonar.go.coverage.reportPaths=coverage.out

env:
  global:
    secure: XcFDsRJ7kJgA+xrBaue4XfWV5mdyz3gqbQczhb6XVVxgx5hkKegFKN/VNGLxDm0loCrEOA6g+gmbwDmLnQSQW7hECKkRtrbEzu51VUkmk5kDZjvXMdVuCOKpskdsIPo+mGHltb47bs7LEBWzr5QyahIjEF+Gpjz2TIDrJpI24PJK4x79KmDBgoHbFU63yGFhl409tAFVyqieeayRGcHctU44c/2UWsxG/d13DLFWj70YEXpqV4zw0nb+z2f29oUNCjULHjdIQrRz/h0ZP2Lqh6WP1geRV/dN0a06Mdf3TDU3R5E+qez2zjkRdGD2hBeuefu0NrRXFq58O8qAhhenMpH2NzbzhiHAwpPQDsopu9Oo/1/e0WBnejS3igiHSqQFSn3UH+J/OLuMd1dTWm9iQGWqY4c36P9eM5MJPpTCryWJB+qZcBPT+kvyRq5Hj3LrnRhxXCZX/9tszccNmoE1Ikvu5HILEaRjLp0/p9n/htpEs8NY0eSSmyG4IDUvEXz+x2tUE7TzFpjXgcHyB1KWB1z1KadJhdHAMOJGs7xEpBOYQfWr87GO1qUVGVGXtE4GI4WUHg9SFxWc6C8lGxdiFAIFmSkXYQX9gBh3T/R859ATakgIkgeh+VPi73GUFnODjPgHqql3MTkkExT7bREuQQExtwCC0NMhjToIPN7kpyk=
